### ISSUE TITLE
On translate.habitica.com emails are broken

### ISSUE THREAD

**Issue by RogoTe** [HabitRPG/habitrpg-email-server#15]
![Screenshot_2019-08-13 Interner Serverfehler](https://user-images.githubusercontent.com/45861130/62938119-a921fb80-bdce-11e9-9ae2-623104109b7d.png)
There is a (may be configuration) problem with emails on translate.habitica.com.
In my case I tried to register to weblate and everything looks fine except that the email with the confirmation code is never sent. I run my own mail server, so I can see there clearly is no sign of any incoming mail. Other user from the Commonwealth of i18n also reported this. 
Also trying to report this problem via https://translate.habitica.com/contact/?t=reg ends in an internal server error.

**Comment by paglias** [comment]
Hi @RogoTe and thanks for the report. This repo and the relative server are not used for https://translate.habitica.com but I'll check with the rest of the team about the issue

**Comment by paglias** [comment]
@RogoTe it should be fixed now! let me know if it's not

**Comment by RogoTe** [comment]
@paglias Thanks and sorry for the wrong issue.
To me problem seems to be still there.

**Comment by paglias** [comment]
Hmm @RogoTe can you send an email to admin@habitica.com? specifying the problem, the email you tried to receive and your email address? thanks
