### ISSUE TITLE
Links in messages lead to mandrillapp.com and then get redirected to habitrpg-staging.herokuapp.com

### ISSUE THREAD

**Issue by GitHubSphinx** [HabitRPG/habitrpg-email-server#2]
It seems, that the last messages I'm receiving from HabitRPG have links to mandrillapp.com which then redirects me to habitrpg-staging.herokuapp.com instead of the page of messages/options on habitrpg.com. Is it the intended behavior now?

**Comment by paglias** [comment]
@GitHubSphinx which email?

**Comment by GitHubSphinx** [comment]
Hi, @paglias ! Now I have only messages about receiving a PM in HabitRPG, so I can't be 100% sure about the quest start and other ones. I thought this issue, if it is so, may belong here.

**Comment by GitHubSphinx** [comment]
Everything is back to normal

**Comment by paglias** [comment]
The link depends on where the message was originated, in this case
from habitrpg-staging but it's not meant to be used by the normal
users, probably from someone of the team

2015-05-10 11:34 GMT+02:00, Sphinx <notifications@github.com>:
> Closed #2.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg-email-server/issues/2#event-301107025


-- 
Matteo Pagliazzi - paglias.net
