### ISSUE TITLE
Not all templated fields get populated in `text/plain` mail.

### ISSUE THREAD

**Issue by Gumnos** [HabitRPG/habitrpg-email-server#3]
Today I received a HabitRPG email with the subject "Your Weekly Progress Update".  By default, my mailer (Claws) shows the `text/plain` component and only displays the `text/html` if requested.  In the `text/plain` bit, I encountered this:

    The oldest To-Do that you completed was added on: |OLDEST_TODO_COMPLETED_DATE|*.

which I expect should have been populated with the same date information that was visible in the `text/html` portion.

I poked through the `habitrpg-email-server` project and didn't seen an obvious template that was used, so this might be lodged against the wrong HabitRPG project. If so, I'd gladly report it against whatever one you direct me to instead.

As a side note, there was an extra backslash-escaping of an apostrophe in the same email, "Keep going, and you\'ll earn a 21-Day Streak Achievement!" but again, only in the `text/plain` component (the `text/html` was just fine).

**Comment by paglias** [comment]
@Gumnos thanks for the report! there's a missing charachter in the text/plain version, I've just fixed it and also removed the extra backslash. Next time it should be ok.

I'm sorry for the incovenience, thanks again for the quick report!
